{% set name = "perl-sivg" %}
{% set version = "2.89" %}
{% set sha256 = "74751f6880accbf93b2235161ec459a3d07909928794c90f1adc91b158db7711" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  url: https://cpan.metacpan.org/authors/id/M/MA/MANWAR/SVG-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  noarch: generic
  number: 0
  script:
    - perl Makefile.PL INSTALLDIRS=vendor NO_PERLLOCAL=1 NO_PACKLIST=1
    - make
    - make test
    - make install VERBINST=1

requirements:
  build:
    - make
  host:
    - perl
    - perl-extutils-makemaker
  run:
    - perl

test:
  imports:
    - SVG
    - SVG::DOM
    - SVG::Element
    - SVG::Extension
    - SVG::XML

about:
  home: https://metacpan.org/dist/SVG
  license: GPL-1.0-or-later OR Artistic-1.0-Perl
  license_family: OTHER
  summary: 'Perl extension for generating Scalable Vector Graphics (SVG) documents'
  license_file:
    - {{ environ["PREFIX"] }}/man/man1/perlartistic.1
    - {{ environ["PREFIX"] }}/man/man1/perlgpl.1
    - LICENSE

extra:
  recipe-maintainers:
    - cbrueffer
